### ISSUE TITLE
좋아요 기능 API 작업

### ISSUE THREAD

**Issue by yws1502** [a-daily-diary/ADD.BE#10]
## 💬 작업 설명

- 좋아요 API 개발
- 일기 테이블과 relation 연결
- 로그인한 사용자가 일기 좋아요를 누르면 일기의 favoriteCount 필드의 값 증가, 좋아요를 취소하면 isFavorite 필드의 값 감소
- 로그인한 사용자가 일기 리스트 조회 시 좋아요한 일기의 경우 isFavorite 필드의 값이 true, 아닌 경우는 false로 처리
- 일기 테이블 조회 시 좋아요 테이블의 값을 활용하여 커스텀 필드 생성(isFavorite)

<br />

## ✅ 작업 목록

- [x] #11
- [x] #12
- [x] #13

**Comment by Bori-github** [comment]
PR 크기 너무 커지면 쪼개서 진행하세여!

**Comment by yws1502** [comment]
> PR 크기 너무 커지면 쪼개서 진행하세여!

해당 이슈를 여러번 쪼개서 PR 날리려고 했는데,

이슈 한 개를 여러번 쪼개서 PR을 날려도 되나요?
아니면 Issue를 조금 더 작은 단위로 쪼개어 생성할까요?

**Comment by Bori-github** [comment]
base 이슈(PR)를 두고, 연관 이슈 생성하면서 연결되는 PR들은 base PR로 머지가 되게끔 진행한 후, base PR 작업이 마무리 되면 dev로 머지 진행하는게 좋을 거 같아요.
예) base PR : 좋아요 CRUD API 생성
연관 이슈 및 PR: 좋아요 생성 API 구현, 좋아요 삭제 API 구현 등
연관 PR은 머지 방향이 base PR을 향합니다.
모든 기능이 구현되었을 때 base PR은 dev로 머지를 합니다.
이해가 되게 설명했는지 모르겠네여..

**Comment by yws1502** [comment]
감사합니다 보리님 : )
