### ISSUE TITLE
User Entity 일부 필드 exclude

### ISSUE THREAD

**Issue by yws1502** [a-daily-diary/ADD.BE#22]
## 💬 작업 설명

- User Entity 일부 필드 exclude
    - 제외되는 필드 : password, createAt, updateAt, deleteAt, isAgree

<br />

## ✅ 작업 목록

- [x] user entity 수정 (일부 필드 exclude)
- [x] swagger response example 수정

**Comment by Bori-github** [comment]
제목에 exclude 오타 있네용 홍홍

**Comment by yws1502** [comment]
확인해주셔서 감사합니다~~
